"""Scope strings for API keys (integrations). JWT users use RBAC roles instead."""

BOOKINGS_READ = "bookings:read"
BOOKINGS_WRITE = "bookings:write"
GUESTS_READ = "guests:read"
GUESTS_WRITE = "guests:write"
HOUSEKEEPING_READ = "housekeeping:read"
HOUSEKEEPING_WRITE = "housekeeping:write"
INVENTORY_READ = "inventory:read"
INVENTORY_WRITE = "inventory:write"
RATES_READ = "rates:read"
RATES_WRITE = "rates:write"
PROPERTIES_READ = "properties:read"
PROPERTIES_WRITE = "properties:write"
ROOMS_READ = "rooms:read"
ROOMS_WRITE = "rooms:write"
ROOM_TYPES_READ = "room_types:read"
ROOM_TYPES_WRITE = "room_types:write"
RATE_PLANS_READ = "rate_plans:read"
RATE_PLANS_WRITE = "rate_plans:write"
WEBHOOKS_READ = "webhooks:read"
WEBHOOKS_WRITE = "webhooks:write"
COUNTRY_PACKS_READ = "country_packs:read"
COUNTRY_PACKS_WRITE = "country_packs:write"
